todo_app/config/routes.rb
Rails.application.routes.draw do
	get 'todos', to: 'todos#index'
	get 'todos/list'
	get 'todos/new'
	post 'todos', to: 'todos#create'
	get 'todos/:id', to: 'todos#show', as: 'todo'
	get 'todos/:id/edit', to: 'todos#edit', as:'edit'
	patch 'todos/:id', to: 'todos#update'
	delete 'todos/:id', to: 'todos#destroy'
	get 'todos/:id/completed', to: 'todos#completed', as: 'completed'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todo_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todo_app/app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: :true
end

todo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

todo_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new 
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.save
		@todo.update_attributes(:completed=>false)
		redirect_to todos_path	
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		@todo = Todo.find(params[:id])	
	end

	def update
		@todo = Todo.find(params[:id])
		@todo.update(todo_params)
		redirect_to todos_path
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to todos_path	
	end

	def completed
		@todo = Todo.find(params[:id])
		@todo.update_attributes(:completed=>true)
		redirect_to todos_path
	end

	def list
		@todo = Todo.all
		@todo_completed = Todo.where(completed: true)
		@todo_not_completed = Todo.where(completed: false)
	end

	private 
		def todo_params
			params.require(:todo).permit(:description, :completed)
		end

end
                                                                                    

todo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_app/app/helpers/todos_helper.rb
module TodosHelper
end

todo_app/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="<%= todos_path%>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= todos_list_path%>">List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= todos_new_path%>">Add New ToDo</a>
      </li>
      
    </form>
  </div>
</nav>

todo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

todo_app/app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f|%>

<div class="field" >
	<%= f.label :decription, "Description" %>
	<%= f.text_field :description %>
	</div>

	<div class="field">
	<%= f.submit "Guardar" %>
	</div>
	
	<%end%>	

todo_app/app/views/todos/edit.html.erb
<h1>Edit ToDo</h1>


<%= render 'todos/form'%>

<div>
	<%= link_to 'Back', todos_path, :class => 'btn btn-info' %>
</div>

todo_app/app/views/todos/index.html.erb
<h1>ToDo List</h1>

<table class=table table-well>	
	<thead>
		<tr>
			<th>Description</th>
			<th>Completed</th>
</thead>
<tbody>

	<% @todos.each do |todo| %>
	<tr>
	<td><%=todo.description %></td>
	<td><%=todo.completed%></td>
	<td><%=link_to 'Show ToDo',todo, :class => 'btn btn-info' %></td>
	<td><%=link_to 'Edit ToDo',edit_path(todo), :class => 'btn btn-success' %></td>
    <td><%=link_to 'Delete ToDo', { :action => :destroy, :id => todo.id }, :method => :delete, :data => { :confirm => 'Are you sure?'},:class=> 'btn btn-danger' %></td>
    <td><%=link_to 'Completed ToDo',completed_path(todo), :class => 'btn btn-warning' %></td>
</tr>
</div>
</tbody>
<%end%>
</table>

todo_app/app/views/todos/list.html.erb
<h1>ToDo List</h1>

<div class="row">
<div class="col-md-6">
<table class="table table-well">
	<thead>
		<tr>
		<th>ToDo Not Completed:</th>
		</tr>
	</thead>
	<tbody>
		<% @todo_not_completed.each do |todo|%>
		<tr>
			<td><%= todo.description %></td>
			<% end %>
		</tr>
	</tbody>
</table>	
</div>

<div class="col-md-6">
<table class="table table-well">
	<thead>
		<tr>
		<th>ToDo Completed:</th>
		</tr>
	</thead>
	<tbody>
		<% @todo_completed.each do |todo|%>
		<tr>
			<td><%= todo.description %></td>
			<% end %>
		</tr>
	</tbody>
</table>	
</div>		
</div>

todo_app/app/views/todos/new.html.erb
<h1>New ToDo</h1>

<%= render 'todos/form'%>

<div>
	<%= link_to 'Back', todos_path, :class => 'btn btn-info' %>
</div>

	

todo_app/app/views/todos/show.html.erb
<div>
	<p>ID:<%= @todo.id %></p>
	<p>Description:<%= @todo.description %> </p>
	<p>Completed?:<%= @todo.completed %></p>
	<%= link_to 'Volver',todos_path,:class => 'btn btn-primary'%>
</div>